# Generated by Django 3.2.9 on 2021-11-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='tags', to='tasks.Task'),
        ),
    ]
